package:
  name: mdsrv
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.3.5')}}

source:
  path: ../../
  
build:
  number: 1
  script: python setup.py install 

requirements:
  build:
    - python
    - cython
    - numpy
    - msinttypes # [win and py2k]
    - setuptools
    - flask
    - scipy
    - zlib
    - mdtraj
    - mdanalysis # [not win and py2k]

  run:
    - python
    - setuptools
    - numpy
    - flask
    - mdtraj
    - mdanalysis # [not win and py2k]

test:
  imports:
    - mdsrv

about:
  home: https://github.com/arose/mdsrv
  license: MIT License
  summary: "Simple server to visualize remote trajectories."
  description: |
    MDsrv is a simple server that enables remote access to coordinate trajectories from molecular dynamics simulations. It can be used together with the NGL Viewer (http://github.com/arose/ngl) to interactively view trajectories of molecular complexes in a web-browser, either within a local network or from anywhere over the internet.
  dev_url: https://nglviewer.org/mdsrv